data:
  image_width: 200  # Длина 
  image_height: 4   # Высота
  num_channels: 1
  
generation:
  line_width: 10
  gap_width: 10
  distortion_types:
  - blur
  - noise
  - scratch
  - lighting
  - combined
  - noise_scratch_blur
  - spot
  
diffusion:
  timesteps: 1000
  beta_schedule: "linear"
  beta_start: 0.0001
  beta_end: 0.02
  
training:
  batch_size: 32
  learning_rate: 1e-3
  epochs: 100
  save_interval: 10
  
model:
  base_channels: 64
  channel_mults: [1, 2, 4, 8]
  num_res_blocks: 2
  attention_resolutions: [16]
  dropout: 0.1
  cond_embed_dim: 128